name: Create release PRs

on:
  create

jobs:
  build:

    runs-on: macOS-latest

    if: contains(github.ref, 'release') # allow to filter on release branches only
    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: bundle install
    - name: Prepare release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CI }}
      run: bundle exec fastlane create_release_pr
